// Dev fallback for `npm run dev`: the REAL payload exported from the committed
// demo run (docs/demo/sample-report/), generated by `report_payload.build()`.
// Not fabricated — regenerate with:
//   python -c "import json;from agentdiff.report_payload import build;\
//   json.dump(build('docs/demo/sample-report'), open('frontend/src/sample.json','w'))"
import sampleJson from "./sample.json";
import type { ReportData } from "./types";

export const SAMPLE = sampleJson as unknown as ReportData;
