"""ship readiness schema: run report payload, api key name, org plan, audit log, usage counter

Revision ID: 0c7fdcec7587
Revises: e3f4a5b6c7d8
Create Date: 2026-07-05 18:01:08.018818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c7fdcec7587'
down_revision: Union[str, Sequence[str], None] = 'e3f4a5b6c7d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add Run.report_payload, ApiKey.name, Org.plan, AuditLog, UsageCounter."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=255), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_org_id_created_at', 'audit_logs', ['org_id', 'created_at'], unique=False)
    op.create_table('usage_counters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.String(length=6), nullable=False),
    sa.Column('runs', sa.Integer(), server_default='0', nullable=False),
    sa.Column('trajectories', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_usage_counters_org_id_period', 'usage_counters', ['org_id', 'period'], unique=True)
    op.add_column('api_keys', sa.Column('name', sa.String(length=120), nullable=True))
    op.add_column('orgs', sa.Column('plan', sa.String(length=20), server_default='free', nullable=False))
    op.add_column('runs', sa.Column('report_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'report_payload')
    op.drop_column('orgs', 'plan')
    op.drop_column('api_keys', 'name')
    op.drop_index('ix_usage_counters_org_id_period', table_name='usage_counters')
    op.drop_table('usage_counters')
    op.drop_index('ix_audit_logs_org_id_created_at', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
